//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuPhat
    {
        public int MaPhieuPhat { get; set; }
        public int MaPhieuMuon { get; set; }
        public int MaDocGia { get; set; }
        public Nullable<System.DateTime> NgayPhat { get; set; }
        public string LyDo { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}
